=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end

def numdivisors(n)
	return 1 if n == 1
	numdiv = 2
	limit = Math.sqrt(n)
	for i in 2..limit do
		if (n % i == 0)
			numdiv += 2
		end
	end
	numdiv -= 1 if limit.truncate ==  limit
	return numdiv
end

def trinumber(n)
	sum = 0
	for i in 1..n do
		sum += i
	end
	return sum
end

nth = 1
trinum = trinumber(nth)
numdiv = numdivisors(trinum)

#puts "n is #{nth}... trinum is #{trinum}... divisors is #{numdiv}"

while numdiv <= 500 do
	nth += 1
	trinum += nth
	numdiv = numdivisors(trinum)
end

puts "n is #{nth}... trinum is #{trinum}... divisors is #{numdiv}"

#150s