#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sumEven = 0
nextFib = 0
previous1 = 2
previous2 = 1

while previous1 < 4000000 do
	if previous1 % 2 == 0
		sumEven += previous1
	end
	nextFib = previous1 + previous2
	previous2 = previous1
	previous1 = nextFib
end

puts "Sum of all even-valued terms is #{sumEven}"